apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: Loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: View Trace

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: Loki
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: Prometheus
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: 15s
